---
title: "rePurIST"
author:
- name: Heewon Seo
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rePurIST}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction
Replication of Purity Independent Subtyping of Tumors (PurIST) that was 
published in the Clinical Cancer Research (Rashid and Peng et al, 2020; 
DOI: 10.1158/1078-0432.CCR-19-1467).

## Install the package
```{r install, eval=FALSE}
intall.packages("devtools")
library(devtools)
devtools::install_github("lootpiz/rePurIST")
```

## Load the package
```{r setup}
library(rePurIST)
```

## A single sample classicifaction
```{r example, eval=FALSE}
prob = PurIST(dat)
```

## MetaGxPancreas subtyping
```{r metagx}
library(MetaGxPancreas)
library(rePurIST)

esets = MetaGxPancreas::loadPancreasEsets()[[1]]

probabilities <- c(); edx <- 1
for(eset in esets) {
    eset_name <- names(esets)[edx]
    edx <- edx +1

    data <- exprs(eset)
    for(idx in c(1:ncol(data))) {
        dat <- as.vector(data[,idx])
        names(dat) <- rownames(data)
        obj <- try(PurIST(dat), silent=TRUE)
        if(is(obj, "try-error")) { prob <- NA } else { prob <- obj }
        result <- cbind(eset_name, colnames(data)[idx], prob)
        probabilities <- rbind(probabilities, result)
    }
}

subtype <- rep(NA, nrow(probabilities))
subtype[which(as.numeric(probabilities[,3]) > 0.5)] <- "Basal-like"
subtype[which(as.numeric(probabilities[,3]) <= 0.5)] <- "Classical"

subtype_results <- data.frame(study = probabilities[,1], sample = probabilities[,2], prob = probabilities[,3], subtype = subtype)

tapply(subtype_results$study, subtype_results$subtype, summary)
```
